from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 579)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        MainWindow.setAcceptDrops(False)
        MainWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.salary = QtWidgets.QLabel(self.centralwidget)
        self.salary.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.salary.setObjectName("salary")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 10, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.rbSingle = QtWidgets.QRadioButton(self.centralwidget)
        self.rbSingle.setGeometry(QtCore.QRect(360, 60, 81, 21))
        self.rbSingle.setObjectName("rbSingle")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rbSingle)
        self.rbMarriedFilingJointly = QtWidgets.QRadioButton(self.centralwidget)
        self.rbMarriedFilingJointly.setGeometry(QtCore.QRect(500, 60, 121, 21))
        self.rbMarriedFilingJointly.setObjectName("rbMarriedFilingJointly")
        self.buttonGroup.addButton(self.rbMarriedFilingJointly)
        self.rbQualifiedWindow = QtWidgets.QRadioButton(self.centralwidget)
        self.rbQualifiedWindow.setGeometry(QtCore.QRect(250, 90, 91, 21))
        self.rbQualifiedWindow.setObjectName("rbQualifiedWindow")
        self.buttonGroup.addButton(self.rbQualifiedWindow)
        self.rbMarriedFillingSingle = QtWidgets.QRadioButton(self.centralwidget)
        self.rbMarriedFillingSingle.setGeometry(QtCore.QRect(360, 90, 131, 21))
        self.rbMarriedFillingSingle.setObjectName("rbMarriedFillingSingle")
        self.buttonGroup.addButton(self.rbMarriedFillingSingle)
        self.rbHeadofHouseHold = QtWidgets.QRadioButton(self.centralwidget)
        self.rbHeadofHouseHold.setGeometry(QtCore.QRect(500, 90, 131, 21))
        self.rbHeadofHouseHold.setObjectName("rbHeadofHouseHold")
        self.buttonGroup.addButton(self.rbHeadofHouseHold)
        self.rbAll = QtWidgets.QRadioButton(self.centralwidget)
        self.rbAll.setGeometry(QtCore.QRect(250, 60, 82, 17))
        self.rbAll.setObjectName("rbAll")
        self.buttonGroup.addButton(self.rbAll)
        self.displayTextField = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.displayTextField.setEnabled(False)
        self.displayTextField.setGeometry(QtCore.QRect(240, 140, 531, 241))
        self.displayTextField.setObjectName("displayTextField")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 360, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.txtSalary = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSalary.setGeometry(QtCore.QRect(60, 60, 113, 20))
        self.txtSalary.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.txtSalary.setObjectName("txtSalary")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
       

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.salary.setText(_translate("MainWindow", "Salary "))
        self.label_2.setText(_translate("MainWindow", "Marginal Tax"))
        self.rbSingle.setText(_translate("MainWindow", "Single"))
        self.rbMarriedFilingJointly.setText(_translate("MainWindow", "Married Filing Jointly"))
        self.rbQualifiedWindow.setText(_translate("MainWindow", "Qualified Widow"))
        self.rbMarriedFillingSingle.setText(_translate("MainWindow", "Married Filing Single"))
        self.rbHeadofHouseHold.setText(_translate("MainWindow", "Head of House Hold"))
        self.rbAll.setText(_translate("MainWindow", "All"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))
